// Tailwind config used ONLY to compile the design-system stylesheet that ships
// to claude.ai/design (`.design-sync/.cache/ds.css`). It is the repo's own config
// plus two additions:
//
//  1. `content` also scans `.design-sync/previews/` so classes used by preview
//     cards actually exist in the compiled CSS.
//  2. a `safelist` of the utility vocabulary a design agent is likely to reach
//     for. Tailwind JIT only emits classes it can SEE, and the agent writes new
//     markup we can never scan — without this, `p-6`, `gap-3` or `bg-app-panel`
//     in a generated design resolve to nothing and the screen renders unstyled.
//
// Keep the app config as the single source of theme truth — only add here.
const base = require('../tailwind.config.cjs');

const APP_COLORS = 'bg|panel|border|text|muted|accent|accent-fg|titlebar';
const SPACE = '0|0\\.5|1|1\\.5|2|2\\.5|3|3\\.5|4|5|6|7|8|9|10|11|12|14|16|20|24|28|32|px';
const STATES = ['hover', 'focus', 'focus-visible', 'active', 'disabled', 'group-hover'];

module.exports = {
  ...base,
  content: [
    './index.html',
    './src/**/*.{jsx,tsx}',
    './.design-sync/previews/**/*.{jsx,tsx}',
    './.design-sync/lokus-root.jsx',
  ],
  safelist: [
    // ── Lokus theme colours, with opacity modifiers and interaction states ──
    {
      pattern: new RegExp(`^(bg|text|border|ring|divide|fill|stroke)-app-(${APP_COLORS})(\\/(5|10|20|30|40|50|60|70|80|90))?$`),
      variants: STATES,
    },
    // ── semantic + neutral colours used by destructive/success states ──
    {
      pattern: /^(bg|text|border)-(red|green|amber|blue|emerald|zinc|white|black|transparent|current)(-(300|400|500|600))?(\/(10|20|30|50))?$/,
      variants: ['hover'],
    },
    // ── spacing ──
    { pattern: new RegExp(`^(p|px|py|pt|pb|pl|pr|m|mx|my|mt|mb|ml|mr|gap|gap-x|gap-y|space-x|space-y)-(${SPACE})$`), variants: ['sm', 'md', 'lg'] },
    { pattern: /^-?(mt|mb|ml|mr|mx|my)-(1|2|3|4|5|6|8)$/ },
    // auto margins — `mr-auto` is the standard escape from a `justify-end` footer
    // and is NOT generated by the app's own scan (the dialog batch hit this).
    { pattern: /^(m|mx|my|mt|mb|ml|mr)-auto$/ },
    // ── sizing ──
    { pattern: new RegExp(`^(w|h|min-w|min-h)-(${SPACE}|full|screen|fit|auto|min|max)$`), variants: ['sm', 'md', 'lg'] },
    // fractional widths — the app only happens to use a few, so the rest silently no-op
    { pattern: /^(w|h)-(1\/2|1\/3|2\/3|1\/4|2\/4|3\/4|1\/5|2\/5|3\/5|4\/5|1\/6|5\/6|1\/12|5\/12|7\/12|11\/12)$/, variants: ['sm', 'md', 'lg'] },
    { pattern: /^(w|h)-(16|20|24|32|40|48|56|64|72|80|96)$/ },
    { pattern: /^max-w-(xs|sm|md|lg|xl|2xl|3xl|4xl|5xl|6xl|7xl|full|none|prose|screen-sm|screen-md|screen-lg)$/ },
    { pattern: /^max-h-(full|screen|none|32|40|48|56|64|72|80|96)$/ },
    // ── layout ──
    { pattern: /^(flex|inline-flex|grid|inline-grid|block|inline-block|inline|hidden|contents)$/, variants: ['sm', 'md', 'lg'] },
    { pattern: /^(flex-(row|row-reverse|col|col-reverse|wrap|nowrap|1|auto|initial|none|grow|shrink)|shrink-0|grow-0|basis-(0|full|auto|1\/2|1\/3|2\/3|1\/4))$/, variants: ['sm', 'md', 'lg'] },
    { pattern: /^(items|justify|content|self|place-items|place-content)-(start|end|center|between|around|evenly|stretch|baseline|auto)$/, variants: ['sm', 'md', 'lg'] },
    { pattern: /^(grid-cols|grid-rows|col-span|row-span)-(1|2|3|4|5|6|7|8|9|10|11|12|full|none)$/, variants: ['sm', 'md', 'lg'] },
    { pattern: /^(relative|absolute|fixed|sticky|static)$/ },
    { pattern: /^(inset|top|bottom|left|right)-(0|1|2|3|4|6|8|auto|full|px)$/ },
    { pattern: /^z-(0|10|20|30|40|50|auto)$/ },
    { pattern: /^(overflow|overflow-x|overflow-y)-(auto|hidden|visible|scroll|clip)$/ },
    // ── typography ──
    { pattern: /^text-(xs|sm|base|lg|xl|2xl|3xl|4xl|5xl)$/, variants: ['sm', 'md', 'lg'] },
    { pattern: /^(font-(thin|light|normal|medium|semibold|bold|extrabold|mono|sans)|italic|not-italic|uppercase|lowercase|capitalize|normal-case|underline|no-underline|line-through|truncate|tabular-nums)$/ },
    { pattern: /^(text-(left|center|right|justify)|leading-(none|tight|snug|normal|relaxed|loose|3|4|5|6|7|8)|tracking-(tighter|tight|normal|wide|wider))$/ },
    { pattern: /^(whitespace-(normal|nowrap|pre|pre-wrap|pre-line)|break-(words|all|normal)|line-clamp-(1|2|3|4|5|6))$/ },
    { pattern: /^(list-(none|disc|decimal|inside|outside))$/ },
    // ── borders, radius, shadow ──
    { pattern: /^(border|border-(0|2|4|8|t|b|l|r|x|y)|border-(t|b|l|r)-(0|2|4))$/ },
    { pattern: /^rounded(-(none|sm|md|lg|xl|2xl|3xl|full))?(-(t|b|l|r|tl|tr|bl|br))?$/ },
    { pattern: /^(shadow(-(sm|md|lg|xl|2xl|inner|none))?|ring(-(0|1|2|4|8|inset))?|ring-offset-(0|1|2|4))$/, variants: ['hover', 'focus', 'focus-visible'] },
    // ── effects / interaction ──
    { pattern: /^(opacity-(0|5|10|20|25|30|40|50|60|70|75|80|90|95|100))$/, variants: ['hover', 'focus', 'disabled', 'group-hover'] },
    { pattern: /^(cursor-(pointer|default|not-allowed|text|grab|wait)|select-(none|text|all|auto)|pointer-events-(none|auto)|resize(-none|-y|-x)?)$/ },
    { pattern: /^(transition(-(all|colors|opacity|shadow|transform))?|duration-(75|100|150|200|300|500|700|1000)|ease-(linear|in|out|in-out)|animate-(spin|ping|pulse|bounce))$/ },
    { pattern: /^(scale|rotate|translate-x|translate-y)-(0|1|2|45|90|95|100|105|110|180)$/, variants: ['hover', 'group-hover'] },
    { pattern: /^(object-(cover|contain|fill|none)|aspect-(auto|square|video))$/ },
    // ── prose (markdown surfaces) ──
    { pattern: /^prose(-(sm|base|lg|xl|invert))?$/ },
  ],
};
