blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/CodeWithInferno/Lokus/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/CodeWithInferno/Lokus/wiki
    about: Check our documentation and guides
  - name: 💡 Ideas & Feedback
    url: https://github.com/CodeWithInferno/Lokus/discussions/categories/ideas
    about: Share ideas and provide feedback on existing features