#!/bin/bash

# Git Worktree Creation Script
# Usage: ./create-worktree.sh <worktree-name> [base-port]

set -e

WORKTREE_NAME=$1
MANUAL_PORT=$2

if [ -z "$WORKTREE_NAME" ]; then
    echo "Usage: $0 <worktree-name> [base-port]"
    echo "Example: $0 feature-auth"
    echo "Example: $0 feature-auth 1450  (manual port)"
    exit 1
fi

# Get the script's directory and navigate to git root
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
GIT_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"
cd "$GIT_ROOT"

# Determine workspaces directory
if [ -d "../workspaces" ]; then
    WORKSPACES_DIR="$( cd ../workspaces && pwd )"
else
    echo "Creating workspaces directory..."
    mkdir -p "../workspaces"
    WORKSPACES_DIR="$( cd ../workspaces && pwd )"
fi

WORKTREE_PATH="$WORKSPACES_DIR/$WORKTREE_NAME"

# Check if worktree already exists
if [ -d "$WORKTREE_PATH" ]; then
    echo "❌ Worktree already exists at: $WORKTREE_PATH"
    exit 1
fi

# Allocate ports (auto or manual)
if [ -n "$MANUAL_PORT" ]; then
    BASE_PORT=$MANUAL_PORT
    HMR_PORT=$((MANUAL_PORT + 1))
    echo "Using manual ports: $BASE_PORT (Vite), $HMR_PORT (HMR)"
else
    echo "🔍 Finding available ports..."
    PORT_JSON=$(node "$SCRIPT_DIR/find-free-port.js" allocate "$WORKTREE_NAME")
    BASE_PORT=$(echo "$PORT_JSON" | node -pe "JSON.parse(require('fs').readFileSync(0)).vitePort")
    HMR_PORT=$(echo "$PORT_JSON" | node -pe "JSON.parse(require('fs').readFileSync(0)).hmrPort")
    echo "✅ Auto-assigned ports: $BASE_PORT (Vite), $HMR_PORT (HMR)"
fi

# Check if branch already exists
if git show-ref --verify --quiet refs/heads/$WORKTREE_NAME; then
    echo "⚠️  Branch '$WORKTREE_NAME' already exists. Creating worktree from existing branch..."
    git worktree add "$WORKTREE_PATH" "$WORKTREE_NAME"
else
    echo "Creating new branch '$WORKTREE_NAME' and worktree..."
    git worktree add -b "$WORKTREE_NAME" "$WORKTREE_PATH"
fi

# Setup environment file
echo "Setting up environment..."
cat > "$WORKTREE_PATH/.env.local" <<EOF
# Worktree-specific environment variables
# Auto-generated by create-worktree.sh on $(date)

VITE_PORT=$BASE_PORT
VITE_HMR_PORT=$HMR_PORT
EOF

# Generate Tauri worktree config
echo "Generating Tauri configuration..."
mkdir -p "$WORKTREE_PATH/src-tauri"
cat > "$WORKTREE_PATH/src-tauri/tauri.worktree.conf.json" <<EOF
{
  "\$schema": "https://schema.tauri.app/config/2.0.0",
  "build": {
    "beforeDevCommand": "npm run dev",
    "devUrl": "http://localhost:$BASE_PORT",
    "beforeBuildCommand": "npm run build",
    "frontendDist": "../dist"
  }
}
EOF

# Create symlink to node_modules (to save disk space)
echo "Linking node_modules..."
if [ -d "$GIT_ROOT/node_modules" ]; then
    ln -s "$GIT_ROOT/node_modules" "$WORKTREE_PATH/node_modules"
    echo "✅ node_modules symlinked"
else
    echo "⚠️  No node_modules found in main repo. Run 'npm install' in main repo first."
fi

echo ""
echo "✅ Worktree created successfully!"
echo ""
echo "📁 Location: $WORKTREE_PATH"
echo "🌿 Branch: $WORKTREE_NAME"
echo "🔌 Ports: $BASE_PORT (Vite), $HMR_PORT (HMR)"
echo ""
echo "Next steps:"
echo "  cd $WORKTREE_PATH"
echo "  npm run dev"
echo "  # Or with Tauri:"
echo "  npm run tauri dev --config src-tauri/tauri.worktree.conf.json"
echo ""
